# Generated by Django 5.2.3 on 2026-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_venue_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
