# Generated by Django 5.2.3 on 2026-03-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='preferred_month',
            field=models.CharField(default='', max_length=20),
        ),
    ]
