# Generated by Django 5.2.3 on 2026-03-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_user_email_user_password_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
